title: 'NetNote'
description: '只要学不死，就往死里学！'
locales:
  '/':
    lang: 'zh-CN'
base: /
head:
  - ["link", { rel: 'icon', href: '/img/logo.png' }]
  - ['link', { rel: 'manifest', href: '/manifest.webmanifest' }]
  - ['meta', { name: 'theme-color', content: '#3eaf7c' }]
  - ['meta', { name: 'apple-mobile-web-app-capable', content: 'yes' }]
  - ['meta', { name: 'apple-mobile-web-app-status-bar-style', content: 'black' }]
  - ['link', { rel: 'apple-touch-icon', href: '/img/logo_192.png' }]
  - ['meta', { name: 'msapplication-TileImage', content: '/img/logo_192.png' }]
  - ['meta', { name: 'msapplication-TileColor', content: '#000000' }]
themeConfig:
  nav:
    -
      text: 起步
      items: 
        -
          text: 开始项目
          link: /start/start.html
        -
          text: GitHub 使用方法
          link: /start/use_GitHub/
        -
          text: VScode 使用方法
          link: /start/use_VScode/
        -
          text: IDEA 使用方法
          link: /start/use_IDEA/
        -
          text: Markdown 语法
          link: /start/markdown.html
        -
          text: mermaid 语法
          link: /start/mermaid.html
        -
          text: YAML 语法
          link: /start/yaml.html
    -
      text: 编程
      items:
        -
          text: Web 前端
          link: /coding/Web/
        -
          text: Java
          link: /coding/Java/
        -
          text: Spring Projects
          link: /coding/Spring/
        -
          text: MariaDB
          link: /coding/MariaDB/
        -
          text: Redis
          link: /coding/Redis/
        -
          text: RabbitMQ
          link: /coding/RabbitMQ/
        -
          text: Docker
          link: /coding/Docker/
    -
      text: 网络搭建
      items:
        -
          text: 网络基础
          link: /net/01-base/
        -
          text: 交换机配置
          link: /net/switch/
        -
          text: 路由器配置
          link: /net/router/
        -
          text: 无线配置
          link: /net/acap/
        -
          text: 安全配置
          link: /net/security/
        -
          text: 广域网配置
          link: /net/wan/
        -
          text: 参考手册
          items:
            -
              text: 操作手册
              link: /net/manual/operate/
            -
              text: 命令手册
              link: /net/manual/command/
        -
          text: 思科模拟器
          items:
            -
              text: Cisco Packet Tracer Help
              link: https://help.cisco.yueplus.ink/Simplified%20Chinese/
            -
              text: GitHub
              link: https://github.com/Yue-plus/cisco_packet_tracer_help
    -
      text: 系统服务
      items:
        - 
          text: 云平台与虚拟机
          link: /serve/VM/
        -
          text: Windows Server
          link: /serve/WS/
        -
          text: Linux
          link: /serve/Linux/
    -
      text: Gitee
      link: https://gitee.com/yue_plus/NetNote
  sidebar:
    '/start/':
      - 'start'
      - 'use_GitHub/'
      - 'use_VScode/'
      - 'use_IDEA/'
      - 'markdown'
      - 'mermaid'
      - 'yaml'
    '/coding/Spring/Framework/WebServlet/':
      - '../../'
      - '1.SpringWebMVC'
      - '2.REST_Clients'
      - '3.Testing'
      - '4.WebSockets'
      - '5.OtherWebFrameworks'
    '/coding/':
      - 'Web/'
      - 'Java/'
      - 'Spring/'
      - 'MariaDB/'
      - 'Redis/'
      - 'RabbitMQ/'
      - 'Docker/'
    '/net/manual/command/':
      - '01-1_base'
      - '01-2_FS'
      - '02_interface'
      - '03-1_Vlan'
      - '03-2_MAC'
      - '04_MSTP'
      - '07_DHCP'
      - '08-1_routing-strategy'
      - '08-2_static-routing'
      - '08-3_RIP'
      - '08-4_RIPng'
      - '14-1'
      - '14-2'
      - '14-3'
      - '14-4'
      - '15-1command'
      - '15-2monitor'
      - '16-1_VSF-base'
      - '16-2_VSF-MAD'
      - '16-3_VSF-debug'
      - '17_info-center'
    '/net/manual/operate/':
      - '07_DHCP'
    '/net/':
      - '01-base/'
      - 'switch/'
      - 'router/'
      - 'acap/'
      - 'security/'
      - 'wan/'
    '/serve/VM/':
      - 'DCC-CRL1000/'
      - 'VMware/'
      - 'Hyper-V/'
    '/serve/WS/':
      - 'ActiveDirectoryDomain'
      - 'DHCP'
      - 'WDS'
      - 'DFS'
      - 'NLB'
      - 'FailoverCluster'
    '/serve/Linux/':
      - '01-Base/'
      - '02-Chrony/'
      - '03-NFS/'
      - '04-MariaDB/'
      - '05-Apache/'
      - '06-Tomcat/'
      - '07-Samba/'
      - '08-NIS/'
      - '09-Postfix/'
      - '10-Pacemaker/'
  smoothScroll: true
  sidebarDepth: 2
  lastUpdated: '上次更新'
  repo: 'https://github.com/Yue-plus/NetNote'
  repoLabel: 'GitHub'
  docsBranch: 'main/docs'
  editLinks: true
  editLinkText: '在 GitHub 上编辑此页'
plugins:
  - '@vuepress/active-header-links'
  - '@vuepress/back-to-top'
  - '@vuepress/medium-zoom'
  - '@vuepress/last-updated'
  - '@vuepress/pwa'
  - 'vuepress-plugin-mermaidjs'